### ISSUE TITLE
Report Portal 5.7.0 integration with SauceLabs 5.1.0/5.7.1 plugin is failing

### ISSUE THREAD

**Issue by amsachin** [reportportal/plugin-saucelabs#15]
Hello team,

I have deployed Report Portal 5.7.0 version using Docker. When I tried to Integrate [SauceLabs 5.1.0 plugin](https://search.maven.org/artifact/com.epam.reportportal/plugin-saucelabs/5.1.0/pom)  with  Report Portal 5.7.0 version, ran into an issue. On entering the correct user ID and password, the below error is occurring

```
Caused by: java.lang.AbstractMethodError: Receiver class com.epam.reportportal.saucelabs.SaucelabsExtension does not define or inherit an implementation of the resolved method 'abstract com.epam.reportportal.extension.PluginCommand getIntegrationCommand(java.lang.String)' of interface com.epam.reportportal.extension.ReportPortalExtensionPoint.
	at com.epam.ta.reportportal.core.integration.util.BasicIntegrationServiceImpl.getIntegrationCommand(BasicIntegrationServiceImpl.java:110)
	at com.epam.ta.reportportal.core.integration.util.BasicIntegrationServiceImpl.checkConnection(BasicIntegrationServiceImpl.java:100)
	at com.epam.ta.reportportal.core.integration.impl.CreateIntegrationHandlerImpl.createGlobalIntegration(CreateIntegrationHandlerImpl.java:97)
	at com.epam.ta.reportportal.ws.controller.IntegrationController.createGlobalIntegration(IntegrationController.java:113)
```

So looking at the[ latest MR code change around getIntegrationCommand ](https://github.com/reportportal/plugin-saucelabs/pull/13/files#diff-f6870ac63532da41e0e631adc6f445be6880180f9c999ce5ac65b5de3fb1e957R62), I concluded that the 5.7.0 Report portal is not compatible with 5.1.0 plugin, so I built the new plugin jar by cloning and checking out the latest master code by running ```./gradlew clean build -P version=5.7.1``` command.

With the 5.7.1 plugin, the earlier error `java.lang.AbstractMethodError on getIntegrationCommand()` got resolved, however, I am running into a Null pointer error with ```textEncryptor``` object (BasicTextEncryptor seems to be autowired with Spring). Could you please look into the below ```reportportal/service-api:5.7.0 logs``` and suggest.

```
java.lang.NullPointerException: null
	at com.epam.reportportal.saucelabs.RestClient.buildSauceClient(RestClient.java:49)
	at com.epam.reportportal.saucelabs.TestConnectionCommand.executeCommand(TestConnectionCommand.java:40)
	at com.epam.reportportal.saucelabs.TestConnectionCommand.executeCommand(TestConnectionCommand.java:30)
	at com.epam.ta.reportportal.core.integration.util.BasicIntegrationServiceImpl.checkConnection(BasicIntegrationServiceImpl.java:102)
	at com.epam.ta.reportportal.core.integration.impl.CreateIntegrationHandlerImpl.createGlobalIntegration(CreateIntegrationHandlerImpl.java:97)
```
![Report Portal - Sauce plugin - Integration error](https://user-images.githubusercontent.com/34842789/173919674-881eb308-8e7c-412a-86d0-473f95a01fb1.png)

**Comment by amsachin** [comment]
Thank you @DzmitryHumianiuk & @VolhaKarenko for solving the issue. The new plugin worked great, able to see the Saucelabs results in ReportPortal now.
I have one small request, as per [Report portal documentation](https://reportportal.io/docs/Plugins%3Eupload-plugin), the plugins are available in https://search.maven.org/artifact/com.epam.reportportal/plugin-saucelabs but the 5.7.0 plugin is not available here. Could you please update the documentation or upload the artifact the maven.org. Thanks

**Comment by nowakoo** [comment]
@VolhaKarenko @DzmitryHumianiuk I have the very same issue:
I'm trying to integrate Report Portal with Saucelabs. I installed the latest version of the plugin, inserted Username, Access token and chosen the data center and I'm get the following error:

`An error ocurred while connecting to server: Unclassified error [null]`

This error message tells me nothing, as well as entry in network traffic that I attached:
Could you please help with the integration?
I am using Report Portal v. 5.7.2 and I tried Saucelabs plugin v. 5.7.1 and 5.7.0 (both showed the same error) - plugin-saucelabs-5.7.0-all.jar and  plugin-saucelabs-5.7.1.jar from github (https://github.com/reportportal/plugin-saucelabs/packages/895592?version=5.7.1)

**Comment by VolhaKarenko** [comment]
Hi @nowakoo, I checked the integration on Report Portal 5.7.2 and plugin version 5.7.1, and the connection is successful in my case.
Could you please share the API logs with the error?

**Comment by nowakoo** [comment]
Hello @VolhaKarenko. Could you please tell how to get API logs?

**Comment by VolhaKarenko** [comment]
@nowakoo it depends on the deployment method. For Docker: https://docs.docker.com/engine/reference/commandline/logs/ for Kubernetes: https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-running-pods

**Comment by nowakoo** [comment]
@VolhaKarenko thank you! I will provide API logs as soon as possible.

**Comment by nowakoo** [comment]
@VolhaKarenko here is the error from API logs:

`reportportal-api-1    | java.lang.NullPointerException: null
reportportal-api-1    | 	at com.epam.reportportal.saucelabs.RestClient.buildSauceClient(RestClient.java:49)
reportportal-api-1    | 	at com.epam.reportportal.saucelabs.TestConnectionCommand.executeCommand(TestConnectionCommand.java:40)
reportportal-api-1    | 	at com.epam.reportportal.saucelabs.TestConnectionCommand.executeCommand(TestConnectionCommand.java:30)
reportportal-api-1    | 	at com.epam.ta.reportportal.core.integration.util.BasicIntegrationServiceImpl.checkConnection(BasicIntegrationServiceImpl.java:102)
reportportal-api-1    | 	at com.epam.ta.reportportal.core.integration.impl.CreateIntegrationHandlerImpl.createGlobalIntegration(CreateIntegrationHandlerImpl.java:97)
reportportal-api-1    | 	at com.epam.ta.reportportal.ws.controller.IntegrationController.createGlobalIntegration(IntegrationController.java:113)
reportportal-api-1    | 	at com.epam.ta.reportportal.ws.controller.IntegrationController$$FastClassBySpringCGLIB$$255e9ef9.invoke(<generated>)
reportportal-api-1    | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
reportportal-api-1    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
reportportal-api-1    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
reportportal-api-1    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
reportportal-api-1    | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
reportportal-api-1    | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
reportportal-api-1    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
reportportal-api-1    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
reportportal-api-1    | 	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
reportportal-api-1    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
reportportal-api-1    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
reportportal-api-1    | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
reportportal-api-1    | 	at com.epam.ta.reportportal.ws.controller.IntegrationController$$EnhancerBySpringCGLIB$$e53de5a5.createGlobalIntegration(<generated>)
reportportal-api-1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
reportportal-api-1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
reportportal-api-1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
reportportal-api-1    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
reportportal-api-1    | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
reportportal-api-1    | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
reportportal-api-1    | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
reportportal-api-1    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
reportportal-api-1    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
reportportal-api-1    | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
reportportal-api-1    | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
reportportal-api-1    | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
reportportal-api-1    | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
reportportal-api-1    | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
reportportal-api-1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
reportportal-api-1    | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
reportportal-api-1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
reportportal-api-1    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
reportportal-api-1    | 	at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:125)
reportportal-api-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
reportportal-api-1    | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
reportportal-api-1    | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:180)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
reportportal-api-1    | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
reportportal-api-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
reportportal-api-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
reportportal-api-1    | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
reportportal-api-1    | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
reportportal-api-1    | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
reportportal-api-1    | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
reportportal-api-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
reportportal-api-1    | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
reportportal-api-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
reportportal-api-1    | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
reportportal-api-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
reportportal-api-1    | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
reportportal-api-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
reportportal-api-1    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
reportportal-api-1    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
reportportal-api-1    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
reportportal-api-1    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
reportportal-api-1    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
reportportal-api-1    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
reportportal-api-1    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
reportportal-api-1    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
reportportal-api-1    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
reportportal-api-1    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
reportportal-api-1    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
reportportal-api-1    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
reportportal-api-1    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
reportportal-api-1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
reportportal-api-1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
reportportal-api-1    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
reportportal-api-1    | 	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by VolhaKarenko** [comment]
@nowakoo thanks! the team needs some time for investigations, I'll keep you updated

**Comment by nowakoo** [comment]
Thanks a lot @VolhaKarenko ! Looking forward for the update :)

**Comment by nowakoo** [comment]
Hi @VolhaKarenko! Any update on the issue?

**Comment by VolhaKarenko** [comment]
Hi @nowakoo! I'm sorry for not getting back to you sooner, but the team is currently busy with other tasks. Regarding the issue, unfortunately, we don't have any ideas yet. The problem seems to be in the absence of the value for the "Data center" field, but the field is mandatory and you mentioned that you had specified this value. Just in case, could you please check that this value in Saucelabs is the same as you select on Report Portal side? I would also suggest trying to regenerate the access token in Saucelabs

**Comment by nowakoo** [comment]
Hi @VolhaKarenko ! No problem. I checked Data center and it seems to be correct :
![obraz](https://user-images.githubusercontent.com/58194092/220374394-00dcee74-c0e1-4b1c-b7ae-befa7ea9cc85.png)
![obraz](https://user-images.githubusercontent.com/58194092/220375191-131adf30-b7c1-4c96-8889-f8a1c11e515e.png)
I also regenerated access token and still negative result.

**Comment by nowakoo** [comment]
Hi @VolhaKarenko ! No problem. I checked the data center as you advised and it seems to be correct:
![obraz](https://user-images.githubusercontent.com/58194092/220375656-594bf395-5b2f-4d79-a918-db19d181a9d6.png)
![obraz](https://user-images.githubusercontent.com/58194092/220375978-494e8649-6c9e-4dda-9b54-ec7c832a6a09.png)
I also regenerated the access token and still negative result

**Comment by nowakoo** [comment]
[reportportal.log](https://github.com/reportportal/plugin-saucelabs/files/10794900/reportportal.log)

I also attached full API log from the moment when error appeared.

**Comment by nowakoo** [comment]
Hi @VolhaKarenko! Do you have any other ideas how I can fix this issue?

**Comment by nowakoo** [comment]
Hi @VolhaKarenko. Any update on the issue? I still cannot integrate ReportPortal instance with SauceLabs

**Comment by VolhaKarenko** [comment]
Hi @nowakoo, unfortunately no updates so far
@APiankouski do you have any ideas?

**Comment by nowakoo** [comment]
Hi @VolhaKarenko 
Sorry for bothering you, but I still don't have access to SauceLabs data using the plugin and it would be really beneficial for me if I could have Report Portal integrated with Saucelabs.

**Comment by DzmitryHumianiuk** [comment]
@nowakoo i've just tried it on my end, with the latest version (RP: 5.7.3 and SausePlugin 5.7.1)
and it works for me.

The NullPointerException on your end might be referring to either missing access to SauseLabs API or issues with upload of the plugin.

Please verify 2 things:
1. uninstall plugin. Restart `service-api`. install plugin again.
2. do the ping command from the container of `service-api`to the SauceLabs base api:


Data Center | API Base URL
-- | --
US | https://api.us-west-1.saucelabs.com/
Europe | https://api.eu-central-1.saucelabs.com/
APAC Southeast | https://api.apac-southeast-1.saucelabs.com/

**Comment by nowakoo** [comment]
Thank you @DzmitryHumianiuk @VolhaKarenko!
I needed to restart `service-api` container and now it works :)

**Comment by DzmitryHumianiuk** [comment]
@nowakoo 
![image](https://user-images.githubusercontent.com/11332788/229649629-94bbaa3e-d4d3-476f-b2c1-dda779a500f1.png)
